apiVersion: v1
description: A Helm chart for the HMCTS Probate product
name: probate
version: 2.0.1
icon: https://github.com/hmcts/chart-ccd/raw/master/images/icons8-java-50.png
keywords:
  - probate
