dependencies:
  - name: ccd-elasticsearch
    version: '0.5.3'
    repository: '@hmctspublic'
#   - name: ccd-elasticsearch
#     version: '0.5.2'
#     repository: file:///home/praveen/github/chart-ccd-elasticsearch/ccd-elasticsearch

 