dependencies:
  - name: postgresql
    version: ~5.3.0
    repository: '@stable'
  - name: probate-submit-service
    version: ~0.1.4
    repository: '@hmctspublic'
  - name: probate-business-service
    version: ~0.0.2
    repository: '@hmctspublic'
  - name: probate-orchestrator-service
    version: ~0.0.4
    repository: '@hmctspublic'
  - name: probate-back-office
    version: ~0.0.2
    repository: '@hmctspublic'
  - name: probate-frontend
    version: ~1.0.2
    repository: '@hmctspublic'
  - name: probate-caveats-fe
    version: ~1.0.1
    repository: '@hmctspublic'
  - name: rpe-service-auth-provider
    version: ~0.1.1
    repository: '@hmctspublic'
  - name: cmc-pdf-service
    version: ~0.1.3
    repository: '@hmctspublic'
  - name: fees-register-api
    version: ~0.0.4
    repository: '@hmctspublic'
  - name: payment-api
    version: ~0.0.4
    repository: '@hmctspublic'
  - name: dm-store
    version: ~1.0.1
    repository: '@hmctspublic'
  - name: rpe-send-letter-service
    version: ~0.0.4
    repository: '@hmctspublic'
  - name: ccd
    version: ~3.0.3
    repository: '@hmctspublic'
    tags:
      - ccd-enabled