tags:
  ccd-enabled: true
  ccd-idam-pr: true
  ccd-elasticsearch: true

ccd-elasticsearch:
  logstash:
    elasticsearch:
      host: "{{ .Release.Name }}-ccd-es-client"
  elasticsearch:
    nameOverride: ccd-es
    master:
      persistence:
        enabled: false
    data:
      persistence:
        enabled: false
  ccd:
    ingressHost: '{{ .Values.global.ccdIngress }}'
    idam-pr:
      releaseNameOverride: '{{ .Release.Name }}-idam-pr'
      redirect_uris:
        ccd_gateway:
          - https://case-management-web-{{ .Values.global.ccdIngress }}/oauth2redirect
        ccd_gateway:
          - https://admin-web-{{ .Values.global.ccdIngress }}/oauth2redirect
    definitionStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
      s2sAuthorisedServices: ccd_admin,ccd_data,ccd_gw
    apiGateway:
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret:
        fromSecret: true
        secretKeyRefName: ccd-api-gateway-oauth2-client-secret
        secretKeyRefKey: key
    dataStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
      image: "hmctspublic.azurecr.io/ccd/data-store-api:latest"
    caseManagementWeb:
      enabled: true
    adminWeb:
      enabled: true
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret:
        fromSecret: true
        secretKeyRefName: ccd-api-gateway-oauth2-client-secret
        secretKeyRefKey: key
    importer:
      userRoles:
        - caseworker-probate
        - caseworker-probate-issuer
        - caseworker-probate-solicitor
        - citizen
        - caseworker-probate-examiner
global:
    devMode: true
    postgresqlUsername: hmcts
    postgresqlPassword: hmcts
    bsoIdamRedirectUrl: "https://bulk-scan-orchestrator/oauth2/callback"
    ccdIngress: ""

