tags:
  ccd-enabled: true
  ccd-idam-pr: true
  ccd-elasticsearch: true
  rpe-feature-toggle-api-pod: true
  postgresql-pod: false
  blobstorage: false
  idam-pr: true 


#####################################
##### Probate - Back Office
#####################################
# probate-back-office:
#   java:
#     environment:
#       ingressHost: ""
#       image: hmctspublic.azurecr.io/probate/back-office:latest
#       AUTH_PROVIDER_SERVICE_CLIENT_KEY: AAAAAAAAAAAAAAAA
#       IDAM_CLIENT_NAME: probate
#       PROBATE_POSTGRESQL_USER: probate_man
#       PROBATE_POSTGRESQL_PASSWORD: hmcts
#       PROBATE_POSTGRESQL_DATABASE: hmcts
#       PROBATE_POSTGRESQL_HOSTNAME: "chart-probate-postgresql"
#       PROBATE_POSTGRESQL_PORT: 5432
#       AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-chart-probate"
#       PDF_SERVICE_URL: "http://cmc-pdf-service-chart-probate"
#       PRINTSERVICE_HOST: http://ccd-case-print-service
#       PRINTSERVICE_INTERNAL_HOST: http://ccd-case-print-service
#       CCD_GATEWAY_HOST: http://ccd-api-gateway-web
#       SERVICES_CORECASEDATA_BASEURL : http://ccd-data-store
#       IDAM_SERVICE_HOST:  https://idam-api.demo.platform.hmcts.net
#       FEE_API_URL: "http://fees-chart-probate"
#       EVIDENCE_MANAGEMENT_HOST: "http://dm-store-chart-probate"      
#       SEND_LETTER_SERIVCE_BASEURL: "http://rpe-send-letter-service-chart-probate"
#       IDAM_REDIRECT_URL: "http://{{ .Values.global.probateFrontend }}/oauth2/callback"
#       # IDAM_SECRET: ${IDAM_SECRET}
#       LOG_LEVEL: DEBUG
#       APPINSIGHTS_INSTRUMENTATIONKEY: 00000000-0000-0000-0000-000000000000
#       AUTH_S2S_CLIENT_ID: "probate_backend"

      
#####################################
##### ccd & elasticsearch &Logstash
#####################################
ccd-elasticsearch:
  logstash:
    elasticsearch:
      host: "{{ .Release.Name }}-ccd-es-client"
  elasticsearch:
    nameOverride: ccd-es
    master:
      persistence:
        enabled: false
    data:
      persistence:
        enabled: false
  ccd:
    idamApiUrl: https://idam-api.demo.platform.hmcts.net
    idamWebUrl: https://idam-web-public.demo.platform.hmcts.net
    s2sUrl: "http://rpe-service-auth-provider-chart-probate"
    draftStoreUrl: "http://draft-store-service-chart-probate"
    paymentsUrl: "http://payment-api-chart-probate"
    ingressHost: '{{ .Values.global.ccdIngress }}'
    releaseNameOverride: "ccd-chart-probate"
    userProfileApi:
      environment: 
        USER_PROFILE_DB_HOST: "chart-probate-postgresql"
        IDAM_S2S_URL: "http://rpe-service-auth-provider-chart-probate"
        USER_PROFILE_S2S_AUTHORISED_SERVICES: AAAAAAAAAAAAAAAA
    idam-pr:
      releaseNameOverride: '{{ .Release.Name }}-idam-pr'
      redirect_uris:
        ccd_gateway:
          - https://case-management-web-{{ .Values.global.ccdIngress }}/oauth2redirect
          - https://admin-web-{{ .Values.global.ccdIngress }}/oauth2redirect
    definitionStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
      s2sAuthorisedServices: ccd_admin,ccd_data,ccd_gw
      environment: 
        DEFINITION_STORE_DB_NAME: definition-store
        DEFINITION_STORE_DB_HOST: "chart-probate-postgresql"
        DEFINITION_STORE_DB_USERNAME: hmcts
        DEFINITION_STORE_DB_PASSWORD: hmcts
        DEFINITION_STORE_DB_OPTIONS: "?sslmode=disable"
        ENABLE_DB_MIGRATE: true
    apiGateway:
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret:
        fromSecret: true
        secretKeyRefName: ccd-api-gateway-oauth2-client-secret
        secretKeyRefKey: key
    dataStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
      image: "hmctspublic.azurecr.io/ccd/data-store-api:latest"
      environment: 
        DATA_STORE_DB_NAME: data-store
        DATA_STORE_DB_HOST: "chart-probate-postgresql"
        DATA_STORE_DB_USERNAME: hmcts
        DATA_STORE_DB_PASSWORD: hmcts
        DATA_STORE_DB_OPTIONS: "?sslmode=disable"
        ENABLE_DB_MIGRATE: true
    caseManagementWeb:
      enabled: true
    # testStubsService:
    #   enabled: true
    adminWeb:
      enabled: true
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret:
        fromSecret: true
        secretKeyRefName: ccd-api-gateway-oauth2-client-secret
        secretKeyRefKey: key
    postgresql:
      enabled: false
    importer:
      userRoles:
        - caseworker-probate
        - caseworker-probate-issuer
        - caseworker-probate-solicitor
        - citizen
        - caseworker-probate-examiner

########################

##### DEPENDENCIES #####
rpe-send-letter-service:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/rpe/send-letter-service:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "rpe-send-letter-service-chart-probate"
    environment:
      FILE_CLEANUP_ENABLED: true
      LETTER_TRACKING_DB_HOST: "chart-probate-postgresql"
      LETTER_TRACKING_DB_NAME: "send_letter"
      LETTER_TRACKING_DB_USER_NAME: hmcts
      LETTER_TRACKING_DB_PASSWORD: hmcts
      # LETTER_TRACKING_DB_USER_NAME: '{{ .Values.global.postgresqlUsername }}'
      # LETTER_TRACKING_DB_PASSWORD: '{{ .Values.global.postgresqlPassword }}'
      LETTER_TRACKING_DB_CONN_OPTIONS: ""
      FLYWAY_URL: "jdbc:postgresql://chart-probate-postgresql:5432/send_letter?sslmode=require"
      FLYWAY_NOOP_STRATEGY: "false"
      S2S_URL: "http://rpe-service-auth-provider-chart-probate"
      ENCRYPTION_ENABLED: "false"
      APPINSIGHTS_INSTRUMENTATIONKEY: 00000000-0000-0000-0000-000000000000

dm-store:
  java:
    image: hmctspublic.azurecr.io/dm/store:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    secrets:
      STORAGE_ACCOUNT_NAME:
        disabled: true
      STORAGE_ACCOUNT_KEY:
        disabled: true
      STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:
        disabled: true
    releaseNameOverride: "dm-store-chart-probate"
    environment:
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      ENABLE_AZURE_STORAGE_CONTAINER: 'false'
      POSTGRES_STORAGE_ENABLED: 'true'
      STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=AAAAAAAAAAAAAAAA;AccountKey=AAAAAAAAAAAAAAAA;EndpointSuffix=core.windows.net'
      CASE_WORKER_ROLES: caseworker-probate
      S2S_NAMES_WHITELIST: ccd_gw,ccd_data,ccd_ps,probate_backend,probate_frontend,bulk_scan_orchestrator,bulk_scan_processor
      SPRING_DATASOURCE_URL: "jdbc:postgresql://chart-probate-postgresql:5432/evidence"
      DM_MULTIPART_WHITELIST: image/jpeg,application/pdf,image/tiff,image/png,image/bmp,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.template,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.spreadsheetml.template,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.openxmlformats-officedocument.presentationml.template,application/vnd.openxmlformats-officedocument.presentationml.slideshow
      DM_MULTIPART_WHITELIST_EXT: .jpg,.jpeg,.bmp,.tif,.tiff,.png,.pdf,.txt,.doc,.dot,.docx,.dotx,.xls,.xlt,.xla,.xlsx,.xltx,.xlsb,.ppt,.pot,.pps,.ppa,.pptx,.potx,.ppsx
      MAX_FILE_SIZE: 500MB
      MAX_ACTIVE_DB_CONNECTIONS: 10
      ENDPOINTS_HEALTH_SENSITIVE: false
      ENDPOINTS_INFO_SENSITIVE: false

cmc-pdf-service:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/cmc/pdf-service:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "cmc-pdf-service-chart-probate"

draft-store-service:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/draft-store/service:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "draft-store-service-chart-probate"
    environment:
      DRAFT_STORE_DB_HOST: "chart-probate-postgresql"
      DRAFT_STORE_DB_NAME: draftstore
      DRAFT_STORE_DB_USER_NAME: hmcts
      DRAFT_STORE_DB_PASSWORD: hmcts
      RUN_DB_MIGRATION_ON_STARTUP: true
      DRAFT_STORE_DB_CONN_OPTIONS: ""

fees-register-api:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/fees-register/api:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 45
    livenessPeriod: 45
    releaseNameOverride: "fees-chart-probate"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://chart-probate-postgresql:5432/fees_register"
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      SPRING_LIQUIBASE_ENABLED: true
      ENABLE_FEE_LOADER: true

payment-api:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/payment/api:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "payment-api-chart-probate"
    environment:
      PAYMENT_AUDIT_FILE: /tmp/payment-audit.log
      ASB_CONNECTION_STRING: false
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_DATASOURCE_URL: "jdbc:postgresql://chart-probate-postgresql:5432/payment_api"

rpe-service-auth-provider:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "rpe-service-auth-provider-chart-probate"
    environment:
      TESTING_SUPPORT_ENABLED: 'true'
      MICROSERVICEKEYS_EM_GW: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DATA: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DEFINITION: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_GATEWAY: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_GW: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_DG_DOCASSEMBLY_API: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_PROBATE_BACKEND: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_PROBATE_FRONTEND: AAAAAAAAAAAAAAAA

rpe-feature-toggle-api:
  java:
    ingressHost: ""
    image: hmctspublic.azurecr.io/rpe/feature-toggle-api:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    releaseNameOverride: "rpe-feature-toggle-api-chart-probate"
    importer:
      cron:
        enabled: false
      oneoff:
        enabled: false
    postgresql:
      postgresqlDatabase: "features"
    
postgresql:
  # postgresqlConfiguration: { "maxConnections": 300 }
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "draftstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "fees_register" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "payment_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "send_letter" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "probate" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "probate_man" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "features" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  # postgresqlUsername: '{{ .Values.global.postgresqlUsername }}'
  # postgresqlPassword: '{{ .Values.global.postgresqlPassword }}'
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: user-profile
  persistence:
    enabled: false

########################
global:
    devMode: true
    postgresqlUsername: hmcts
    postgresqlPassword: hmcts
    bsoIdamRedirectUrl: "https://bulk-scan-orchestrator/oauth2/callback"
    ccdIngress: ""
    probateFrontend: ""
